// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3NCQ-aEbkjqh5VNy2D1V-CDqWY0VdUak',
    appId: '1:131778379439:web:8756cc3792cd9f83f6de5a',
    messagingSenderId: '131778379439',
    projectId: 'zona-c4a37',
    authDomain: 'zona-c4a37.firebaseapp.com',
    databaseURL: 'https://zona-c4a37-default-rtdb.firebaseio.com',
    storageBucket: 'zona-c4a37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfQozDHTvY60BkS3SNPMyudVnu4hFmV8I',
    appId: '1:131778379439:android:c14c81c48c44610cf6de5a',
    messagingSenderId: '131778379439',
    projectId: 'zona-c4a37',
    databaseURL: 'https://zona-c4a37-default-rtdb.firebaseio.com',
    storageBucket: 'zona-c4a37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQqbknK9FgvGlTqVQxZ5qgTEchE8eWCEg',
    appId: '1:131778379439:ios:d46b9b6cbeef6c68f6de5a',
    messagingSenderId: '131778379439',
    projectId: 'zona-c4a37',
    databaseURL: 'https://zona-c4a37-default-rtdb.firebaseio.com',
    storageBucket: 'zona-c4a37.appspot.com',
    iosBundleId: 'com.example.zona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQqbknK9FgvGlTqVQxZ5qgTEchE8eWCEg',
    appId: '1:131778379439:ios:e3ce2a06086069fdf6de5a',
    messagingSenderId: '131778379439',
    projectId: 'zona-c4a37',
    databaseURL: 'https://zona-c4a37-default-rtdb.firebaseio.com',
    storageBucket: 'zona-c4a37.appspot.com',
    iosBundleId: 'com.example.zona.RunnerTests',
  );
}
